build:
    dependencies:
        before:
            - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS scrutinizer"
            - sed -i -e 's/DB_DATABASE=motor/DB_DATABASE=scrutinizer/g' .env.testing
            - sed -i -e 's/DB_PASSWORD=123456/DB_PASSWORD=/g' .env.testing
            - php artisan migrate:install
            - php artisan migrate

    tests:
        override:
            -
                command: 'vendor/bin/codecept run functional --coverage --coverage-xml'
                coverage:
                    file: 'tests/_output/coverage.xml'
                    format: 'clover'