before_commands:
    - "cp .env.example .env"
    - "composer install --dev --prefer-source"
    - "php artisan migrate:install"

tools:
    external_code_coverage: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["app/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["build/*", "docs", "test", "vendor"]
    php_cs_fixer:
        enabled: true
        config:
            level: all
        filter:
            paths: ["app/*"]
    php_loc:
        enabled: true
        excluded_dirs: ["build", "docs", "test", "vendor"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["app/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["build", "docs", "test", "vendor"]
    php_analyzer: true
    php_analyzer:
        filter:
            paths: ["app/*"]
    sensiolabs_security_checker: true
