os:
  - linux

language: php

php:
  - '7.2'

before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.example .env
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - php artisan key:generate

script:
  - vendor/bin/phpunit
  - phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers